### ISSUE TITLE
relation "account_base_user" does not exist

### ISSUE THREAD

**Issue by englishwave** [turbulette/turbulette#134]
Hi, I'm a newbie, but I am very interested in this project because I am looking for starlette with jwt authentication, and this is more than expected.

But I have some issues when I am using one of examples: **createUser**.
I installed postgres, and I also set up database connection in .env.
I just thought GINO will automatically create databases and its tables from models.py, but there is no db and no tables.
The below is what I am going through.
Am I missing something related to database?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/graphql/execution/execute.py", line 674, in await_completed
    return await completed
  File "/usr/local/lib/python3.6/dist-packages/graphql/execution/execute.py", line 659, in await_result
    return_type, field_nodes, info, path, await result
  File "/usr/local/lib/python3.6/dist-packages/graphql/execution/execute.py", line 733, in complete_value
    raise result
  File "/usr/local/lib/python3.6/dist-packages/graphql/execution/execute.py", line 628, in await_result
    return await result
  File "/usr/local/lib/python3.6/dist-packages/ariadne/types.py", line 58, in resolve
    result = await result
  File "/usr/local/lib/python3.6/dist-packages/ariadne/utils.py", line 45, in async_wrapper
    return await func(*args, **convert_to_snake_case(kwargs))
  File "/usr/local/lib/python3.6/dist-packages/turbulette/validation/decorators.py", line 35, in wrapped_func
    return await func(obj, info, **kwargs)
  File "./eshop/account/resolvers/user.py", line 38, in resolve_user_create
    user_model.username == valid_input["username"]
  File "/usr/local/lib/python3.6/dist-packages/gino/api.py", line 137, in first
    return await self._query.bind.first(self._query, *multiparams, **params)
  File "/usr/local/lib/python3.6/dist-packages/gino/engine.py", line 748, in first
    return await conn.first(clause, *multiparams, **params)
  File "/usr/local/lib/python3.6/dist-packages/gino/engine.py", line 328, in first
    return await result.execute(one=True)
  File "/usr/local/lib/python3.6/dist-packages/gino/dialects/base.py", line 215, in execute
    context.statement, context.timeout, args, 1 if one else 0
  File "/usr/local/lib/python3.6/dist-packages/gino/dialects/asyncpg.py", line 184, in async_execute
    result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
  File "/usr/local/lib/python3.6/dist-packages/asyncpg/connection.py", line 1681, in _do_execute
    ignore_custom_codec=ignore_custom_codec,
  File "/usr/local/lib/python3.6/dist-packages/asyncpg/connection.py", line 380, in _get_statement
    ignore_custom_codec=ignore_custom_codec,
  File "asyncpg/protocol/protocol.pyx", line 168, in prepare
graphql.error.graphql_error.GraphQLError: relation "account_base_user" does not exist

```

modles.py

```
from gino.json_support import ObjectProperty
from sqlalchemy import Column, DateTime, ForeignKey, Integer
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql.sqltypes import Float, String

from turbulette.db import Model
from turbulette.apps.auth.models import AbstractUser


class BaseUser(Model, AbstractUser):
    pass


class CustomUser(AbstractUser, Model):
    pass

```

resolvers/user.py

```
@mutation.field("createUser")
@convert_kwargs_to_snake_case
@validate(BaseUserCreate)
async def resolve_user_create(*_, **kwargs) -> dict:
    valid_input = kwargs["_val_data"]

    user = await user_model.query.where(
        user_model.username == valid_input["username"]
    ).gino.first()

    if user:
        message = f"User {valid_input['username']} already exists"

        # Make sure to call __str__ on BaseError
        out = str(ErrorField(message))
        logging.info(out)

        return ErrorField(message).dict()

    new_user = await user_model.create(**valid_input)
    auth_token = await get_token_from_user(new_user)
    return {
        "user": {**new_user.to_dict()},
        "token": auth_token,
    }
```

**Comment by englishwave** [comment]
Okay, I fixed the issue since I found the content related to databases from [here](https://turbulette.netlify.app/user_guide/database/).
As the document mentioned, turbulette doesn't do much more from what gino does.
Once put database information into .env, just run turb cli commands as follows: (it shows how to use alembic as well)

```
turb makerevision <app>
turb upgrade <app>
```
